# Generated by Django 2.2.1 on 2019-06-03 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='i_published',
            new_name='is_published',
        ),
    ]
